# UI Constants
FPS = 5
CELL_SIZE = 20
MAX_X = 1280
MAX_Y = 720

# Global Variables
STARTING_DOB_POPULATION = 10
ACTIVE_DOBS = []

STARTING_FOOD_COUNT = 5
ACTIVE_FOOD = []

STARTING_WATER_SOURCES = 5
ACTIVE_WATER = []

# Dob Constants
DOB_TRAITS = {
    "SHORT_TERM_AGE": 3,
    "LONG_TERM_AGE": 25
}